info:
  businessSide: xjjdog
  serviceName: sale-fast-webapp
  author: xjjdog
server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    basedir: ./
    accesslog:
      enabled: true
      directory: /app/Logs/sale-fast-webapp
      pattern: "%{X-Forwarded-For}i %a %{X-B3-TraceId}i %t %m %U %s %b %D"
      rename-on-rotate: true
      suffix: .log
      prefix: access
      rotate: true
      buffered: false
      file-date-format: yyyy-MM-dd
    uri-encoding: UTF-8

spring:
  banner:
    location: banner-girl.txt
  application:
    name: sale-fast-webapp
  http:
    converters:
      preferred-json-mapper: fastjson
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  aop:
    proxyTargetClass: true
    auto: true
  jmx:
    enabled: true
  output:
    ansi:
      enabled: DETECT
  datasource:
    druid:
      url: jdbc:h2:file:D:/salefast/db;AUTO_SERVER=TRUE
      username: xjjdog
      password: xjjdog
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 10000
      #test-while-idle: true
      #validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 15000
      default-auto-commit: true
      min-evictable-idle-time-millis: 30000
      use-global-data-source-stat: true
#      filters: config,stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;
      stat-view-servlet:
        enabled: true
        login-username: xjjdog
        login-password: xjjdog
        reset-enable: false
        allow: 127.0.0.1
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      filter:
        wall:
          enabled: true
          config:
            multi-statement-allow: true
            none-base-statement-allow: true
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        tags: version=1.0,author=yjmyzz
        healthCheckPath: /info.json
        healthCheckInterval: 5s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}


mybatis-plus:
  mapper-locations: classpath*:com/github/**/mapper/xml/*.xml
  typeAliasesPackage: com.github.**.entity
  global-config:
    db-config:
      id-type: AUTO
  configuration:
    # 是否开启自动驼峰命名规则映射，数据库列名sale_type 到Java 属性名 saleType
    map-underscore-to-camel-case: true
    # 使全局的映射器启用或禁用缓存
    cache-enabled: true
    # 全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载。
    lazyLoadingEnabled: false
    # 当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载。
    aggressive-lazy-loading: false
    # 是否可以使用列的别名 (取决于驱动的兼容性) default:true
    use-column-label: true
    # 允许JDBC 生成主键。需要驱动器支持。如果设为了true，这个设置将强制使用被生成的主键，有一些驱动器不兼容不过仍然可以执行。  default:false
    use-generated-keys: false
    # 指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射　PARTIAL:部分  FULL:全部
    auto-mapping-behavior: partial
    # 是否允许单条sql 返回多个数据集  (取决于驱动的兼容性) default:true
    multipleResultSetsEnabled: true
    # 这是默认的执行类型  （SIMPLE: 简单； REUSE: 执行器可能重复使用prepared statements语句；BATCH: 执行器可以重复执行语句和批量更新）
    default-executor-type: simple
    # 设置本地缓存范围 session:就会有数据的共享  statement:语句范围 (这样就不会有数据的共享 ) defalut:session
    local-cache-scope: session
    # 设置但JDBC类型为空时,某些驱动程序 要指定值,default:OTHER，插入空值时不需要指定类型
    jdbc-type-for-null: 'null'
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#管理
management:
  endpoint:
    shutdown:
      enabled: false
    jolokia:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /ops
      exposure:
        include: "*"


swagger:
  title: ${artifactId}
  description: sale fast api document
  version: 1.0.0.RELEASE
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: https://github.com/xjjdog/sale-fast
  contact:
    name: xjjdog
  base-package: ${package}.controller
  base-path: /**
  exclude-path: /error, /ops/**


